# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import TypeAlias

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = ["KennelListResponse", "KennelListResponseItem"]


class KennelListResponseItem(BaseModel):
    arch_string: Optional[str] = None
    """
    used to spawn Agents on demand, pulled from our open source
    [ao_arch repo](https://github.com/aolabsai/ao_arch)
    """

    arch_url: Optional[str] = FieldInfo(alias="arch_URL", default=None)

    description: Optional[str] = None

    kennel_id: Optional[str] = None
    """generated by our backend system"""

    kennel_name: Optional[str] = None

    permissions: Optional[str] = None


KennelListResponse: TypeAlias = List[KennelListResponseItem]
